# .github/workflows/git-sync.yml

on:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@gitee.com:lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_repo: "https://Phil2048:${{ secrets.PAT }}@github.com/Phil2048/test.git"
          destination_branch: "slave"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          github_token: ${{ secrets.PAT }}
